//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKUR
    {
        public int KURID { get; set; }
        public string KURAD { get; set; }
        public string SEMBOL { get; set; }
        public Nullable<decimal> DEGER { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        public virtual TBLDURUM TBLDURUM { get; set; }
    }
}
