//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNHAREKET
    {
        public int HAREKETID { get; set; }
        public Nullable<int> URUN { get; set; }
        public string HAREKETTURU { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual TBLURUN TBLURUN { get; set; }
    }
}
