//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLURUN()
        {
            this.TBLURUNHAREKET = new HashSet<TBLURUNHAREKET>();
        }
    
        public int URUNID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<int> URUNGRUP { get; set; }
        public Nullable<int> URUNBIRIM { get; set; }
        public Nullable<decimal> URUNFIYAT { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
        public Nullable<byte> KDV { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        public virtual TBLBIRIM TBLBIRIM { get; set; }
        public virtual TBLDURUM TBLDURUM { get; set; }
        public virtual TBLURUNGRUP TBLURUNGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURUNHAREKET> TBLURUNHAREKET { get; set; }
    }
}
